CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     VARCHAR(300) NOT NULL,
    available       boolean NOT NULL,
    owner_id        BIGINT REFERENCES users(id),
    request_id      BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id         BIGINT REFERENCES items(id) NOT NULL,
    booker_id       BIGINT REFERENCES users(id) NOT NULL,
    status          VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     VARCHAR(512) NOT NULL,
    requestor_id    BIGINT REFERENCES users(id),
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL

);

CREATE TABLE IF NOT EXISTS comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text            VARCHAR(512) NOT NULL,
    item_id         BIGINT REFERENCES items(id) NOT NULL,
    author_id       BIGINT REFERENCES users(id) NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL
);